const chapters = CHAPTERS;
let currentIndex = 0;
let fontScale = 1;
let mediaRecorder;
let audioChunks = [];
let recordingInterval;
let recordingSeconds = 0;
let translationVisible = false;

const el = (id) => document.getElementById(id);
const chapterList = el("chapterList");
const articleContent = el("articleContent");
const wordList = el("wordList");

const COMMON_WORD_MEANINGS = {
  a: "一个；一（不定冠词）",
  an: "一个；一（用于元音前）",
  and: "和；并且",
  are: "是（be动词复数）",
  as: "作为；像；当...时；由于",
  at: "在...；于...；向",
  be: "是；存在；成为",
  but: "但是；而是；除了",
  by: "通过；被；在...旁边；依据",
  can: "能够；可以；罐头",
  do: "做；进行；产生",
  for: "为了；对于；因为；长达",
  from: "来自；从...；出于",
  had: "有（have过去式/过去分词）",
  has: "有（have第三人称单数）",
  have: "有；拥有；取得；从事",
  he: "他",
  her: "她的；她（宾格）",
  his: "他的",
  i: "我",
  if: "如果；是否",
  in: "在...里；在...期间；输入",
  into: "进入；到...里面；成为",
  is: "是（be动词单数）",
  it: "它；这件事",
  its: "它的",
  of: "...的；关于；由...组成的",
  on: "在...上；关于；继续；开着",
  or: "或者；否则",
  our: "我们的",
  she: "她",
  that: "那个；那；引导从句",
  the: "这/那（定冠词）",
  their: "他们的；她们的；它们的",
  them: "他们；她们；它们",
  there: "那里；存在；在这方面",
  they: "他们；她们；它们",
  this: "这个；这；这事",
  to: "到；向；朝；不定式符号",
  was: "是（be动词过去式单数）",
  we: "我们",
  were: "是（be动词过去式复数）",
  what: "什么；所...的事物",
  when: "当...时候；什么时候",
  where: "哪里；在...的地方",
  which: "哪一个；哪一些；引导从句",
  who: "谁；引导从句",
  will: "将；会；意志；遗嘱",
  with: "和...一起；带有；用；由于",
  you: "你；你们",
  your: "你的；你们的",
  all: "所有的；全部；完全",
  any: "任何的；一些；稍微",
  some: "一些；某些；大约",
  no: "不；没有；绝无",
  not: "不；没有",
  more: "更多的；更加",
  most: "最多的；大多数；最",
  such: "这样的；如此的",
  than: "比（用于比较级）",
  so: "所以；如此；同样",
  about: "关于；大约；周围",
  above: "在...上方；超过",
  across: "穿过；跨越；在...对面",
  after: "在...之后；以后",
  against: "反对；紧贴着；依靠",
  along: "沿着；顺着；一起",
  among: "在...之中；在...中间",
  around: "大约；在...周围；到处",
  before: "在...之前；以前",
  behind: "在...后面；落后于",
  below: "在...下方；低于",
  between: "在...之间",
  beyond: "超出；在...较远的一边",
  down: "向下；沿着",
  during: "在...期间",
  off: "离开；脱落；关掉",
  out: "在外；向外；出于",
  over: "在...上方；越过；超过；结束",
  through: "穿过；通过；自始至终",
  under: "在...下面；少于",
  up: "向上；起来；提高",
  upon: "在...之上；根据",
  within: "在...之内；不超过",
  without: "没有；无",
  also: "也；而且",
  always: "总是；始终",
  away: "离开；远离；消失",
  back: "后退；返回；背部；支持",
  even: "甚至；更加；平坦的；偶数的",
  ever: "曾经；在任何时候",
  far: "遥远的；久远的；极大地",
  just: "仅仅；刚才；正好；公正的",
  never: "从不；绝不",
  often: "经常；常常",
  once: "一次；曾经；一旦",
  only: "仅仅；唯一的；只有",
  quite: "相当；十分；完全",
  still: "仍然；依然；静止的；寂静",
  then: "那时；然后；那么",
  too: "也；太；过分",
  very: "非常；很；恰好是",
  well: "好地；充分地；井；健康的",
  how: "怎样；如何；多少",
  why: "为什么；原因",
  because: "因为",
  although: "虽然；尽管",
  though: "虽然；但是",
  while: "当...的时候；而；然而",
  until: "直到...为止",
  since: "自...以来；因为",
  both: "两者都",
  each: "每个；各自的",
  every: "每一个；所有的",
  other: "其他的；另外的",
  another: "另一个；再一个",
  many: "许多的",
  much: "许多的；很大程度上",
  few: "很少的；几乎没有",
  little: "小的；很少的；稍许",
  own: "自己的；拥有",
  same: "相同的；同一的"
};

const EXTRA_LEARNER_WORDS = {
  ability: "能力；本领",
  able: "有能力的；能干的",
  accept: "接受；同意",
  access: "接触；入口；使用权",
  accident: "事故；意外",
  according: "根据；依照",
  account: "账户；描述；解释",
  achieve: "实现；达到",
  act: "行动；表现；法案",
  action: "行动；作用",
  active: "积极的；活跃的",
  activity: "活动；行动",
  actual: "实际的；真实的",
  actually: "实际上；竟然",
  add: "增加；补充说",
  addition: "增加；附加物",
  address: "地址；演讲；处理",
  adjust: "调整；适应",
  admire: "钦佩；赞赏",
  admit: "承认；准许进入",
  adopt: "采用；收养",
  advance: "前进；提前；提升",
  advantage: "优势；好处",
  advice: "建议；忠告",
  afford: "负担得起；提供",
  afraid: "害怕的；担心的",
  again: "再次；又",
  age: "年龄；时代；变老",
  agree: "同意；一致",
  ahead: "在前面；提前",
  aim: "目标；对准；旨在",
  air: "空气；天空；样子",
  allow: "允许；给予",
  almost: "几乎；差不多",
  alone: "单独的；仅仅",
  alongside: "在...旁边；与...一起",
  already: "已经；早已",
  amount: "数量；总计",
  ancient: "古代的；古老的",
  angle: "角度；视角",
  animal: "动物",
  announce: "宣布；通告",
  another: "另一个",
  answer: "回答；答案；解决办法",
  appear: "出现；显得；看似",
  apply: "申请；应用；适用",
  approach: "靠近；方法；途径",
  area: "区域；面积；领域",
  argue: "争论；主张；论证",
  arm: "手臂；武器；武装",
  around: "周围；大约",
  arrange: "安排；排列",
  arrive: "到达；到来",
  art: "艺术；美术；技术",
  article: "文章；物品；条款",
  ask: "询问；要求；邀请",
  aspect: "方面；外观",
  assume: "假设；认为；承担",
  assumption: "假设；设想",
  attack: "攻击；袭击",
  attempt: "尝试；努力",
  attention: "注意力；关注；关心",
  avoid: "避免；回避",
  baby: "婴儿；幼小的",
  background: "背景；经历",
  bad: "坏的；严重的",
  bag: "袋子；包",
  balance: "平衡；余额；衡量",
  bank: "银行；岸；积累",
  base: "基础；基地；基于",
  basic: "基础的；基本的",
  beautiful: "美丽的；极好的",
  become: "变成；成为",
  bed: "床；底座",
  begin: "开始；动手",
  behavior: "行为；举止",
  behind: "在...后面",
  believe: "相信；认为",
  benefit: "利益；好处；受益",
  best: "最好的；最好地",
  better: "更好的；改善",
  big: "大的；重大的",
  bird: "鸟",
  bit: "一点；少量；碎片",
  black: "黑色的；黑暗",
  blood: "血液；血统",
  blue: "蓝色的；忧郁的",
  board: "木板；董事会；登机",
  body: "身体；主体；尸体",
  book: "书；预订",
  border: "边界；边框",
  born: "出生的；天生的",
  both: "两者都",
  bother: "打扰；烦恼",
  bottom: "底部；末尾",
  box: "盒子；箱子",
  boy: "男孩",
  brain: "大脑；智力",
  branch: "树枝；分支；分部",
  bread: "面包",
  break: "打破；休息；破裂",
  breath: "呼吸；气息",
  breathe: "呼吸",
  bright: "明亮的；聪明的",
  bring: "带来；引致",
  broad: "宽广的；广泛的",
  brother: "兄弟",
  build: "建造；建立",
  building: "建筑物；大楼",
  burn: "燃烧；烧伤",
  business: "商业；生意；事务",
  busy: "忙碌的；繁忙的",
  buy: "购买；买",
  calculate: "计算；估计",
  call: "呼叫；打电话；称呼；要求",
  calm: "平静的；镇静",
  camera: "相机；摄影机",
  card: "卡片；纸牌",
  care: "关心；照顾；小心",
  careful: "仔细的；小心的",
  carry: "携带；运载；支撑",
  case: "情况；案例；箱子",
  catch: "抓住；赶上；理解",
  cause: "原因；导致；事业",
  cell: "细胞；小房间；电池",
  center: "中心；中央",
  central: "中央的；核心的",
  century: "世纪；百年",
  certain: "确定的；某些",
  certainly: "无疑；当然",
  chance: "机会；可能性；偶然",
  change: "改变；变化；零钱",
  channel: "海峡；通道；频道",
  character: "性格；角色；文字",
  charge: "收费；充电；控告；负责",
  cheap: "便宜的；低劣的",
  check: "检查；核对；支票",
  chemical: "化学的；化学品",
  child: "儿童；孩子",
  choice: "选择；挑选",
  choose: "选择；决定",
  circle: "圆圈；循环；圈子",
  city: "城市；都市",
  claim: "声称；索赔；要求",
  class: "班级；阶级；种类",
  clean: "打扫；干净的",
  clear: "清楚的；晴朗的；清除",
  clearly: "清晰地；显然",
  climb: "攀登；上升",
  clock: "钟；时钟",
  close: "关闭；接近的；亲密的",
  cloud: "云；阴影",
  coast: "海岸；海滨",
  code: "代码；密码；准则",
  cold: "寒冷的；冷漠的；感冒",
  collect: "收集；聚集",
  collection: "收集；收藏品",
  color: "颜色；色彩",
  column: "柱子；专栏",
  combination: "结合；组合",
  combine: "结合；合并",
  come: "来；到达；出现",
  comfort: "安慰；舒适",
  comfortable: "舒适的；宽裕的",
  command: "命令；指挥；掌握",
  common: "共同的；常见的；普通",
  community: "社区；共同体",
  company: "公司；陪伴；同伴",
  compare: "比较；对比",
  compete: "竞争；比赛",
  competition: "竞争；比赛",
  complete: "完成；完整的",
  completely: "完全地；彻底",
  complex: "复杂的；综合体",
  computer: "计算机；电脑",
  concentrate: "集中；专心",
  concept: "概念；观念",
  concern: "关心；关切；涉及",
  condition: "条件；状况；环境",
  connect: "连接；联系",
  connection: "连接；关系；联系",
  consider: "考虑；认为",
  consistent: "一致的；持续的",
  constant: "持续的；恒定的",
  contain: "包含；容纳",
  continue: "继续；持续",
  continuous: "连续的；不断的",
  control: "控制；支配；克制",
  convenient: "方便的；近便的",
  conversation: "交谈；对话",
  cook: "烹饪；做饭；厨师",
  cool: "凉爽的；冷静的；酷",
  copy: "复制；副本；一册",
  corner: "角落；街角",
  correct: "正确的；纠正",
  cost: "花费；成本；代价",
  count: "计数；计算；重要",
  country: "国家；乡村",
  couple: "一对；夫妇；几个",
  course: "课程；过程；航向；当然",
  cover: "覆盖；封面；涵盖",
  create: "创造；创作；引起",
  creation: "创造；作品",
  creativity: "创造力；创造性",
  creature: "生物；动物",
  crime: "犯罪；罪行",
  crop: "庄稼；农作物",
  cross: "穿过；交叉；十字架",
  crowd: "人群；拥挤",
  crucial: "关键的；至关重要的",
  culture: "文化；文明",
  cup: "杯子；奖杯",
  curious: "好奇的；古怪的",
  current: "当前的；水流；电流",
  currently: "目前；当前",
  curve: "曲线；弯曲",
  custom: "风俗；习惯；海关",
  customer: "顾客；客户",
  cut: "削减；切；伤口",
  daily: "日常的；每天的",
  damage: "损坏；破坏；损失",
  dance: "跳舞；舞蹈",
  danger: "危险；隐患",
  dangerous: "危险的",
  dark: "黑暗的；深色的",
  data: "数据；资料",
  date: "日期；约会；枣",
  daughter: "女儿",
  day: "白天；一天",
  dead: "死的；枯萎的；完全地",
  deal: "交易；处理；协议",
  dear: "亲爱的；昂贵的",
  decide: "决定；解决",
  decision: "决定；决议",
  deep: "深的；深刻的",
  deeply: "深刻地；深切地",
  defend: "防御；保卫；辩护",
  degree: "程度；度数；学位",
  delay: "延误；推迟",
  delicate: "纤细的；微妙的；易碎的",
  demand: "需求；要求",
  depend: "依赖；取决于",
  describe: "描述；形容",
  description: "描述；描写",
  design: "设计；图案；打算",
  desire: "渴望；愿望",
  desk: "书桌；办公桌",
  despite: "尽管；不管",
  detail: "细节；详述",
  develop: "发展；开发；培养",
  development: "发展；开发",
  device: "设备；装置；手段",
  difference: "差别；差异",
  different: "不同的；各种的",
  difficult: "困难的；难相处的",
  difficulty: "困难；难题",
  direct: "直接的；指导；指向",
  direction: "方向；指导；说明书",
  directly: "直接地；立即",
  disappear: "消失；失踪",
  discover: "发现；发觉",
  discovery: "发现；发觉",
  discuss: "讨论；商讨",
  discussion: "讨论；辩论",
  disease: "疾病；弊病",
  distance: "距离；远方",
  distant: "遥远的；疏远的",
  divide: "分开；分配；除以",
  doctor: "医生；博士",
  dog: "狗",
  door: "门；通道",
  doubt: "怀疑；疑问",
  drive: "驾驶；驱动；推进",
  driver: "司机；驾驶员",
  drop: "落下；滴；下降",
  dry: "干的；干燥的；弄干",
  due: "到期的；预期的；由于",
  during: "在...期间",
  dust: "灰尘；尘土",
  duty: "责任；义务；关税",
  early: "早期的；提前的",
  earn: "赚得；赢得",
  earth: "地球；泥土；陆地",
  ease: "容易；舒适；缓解",
  easily: "容易地；无疑地",
  easy: "容易的；舒适的",
  eat: "吃；腐蚀",
  economic: "经济的；经济学的",
  economy: "经济；节约",
  edge: "边缘；优势",
  education: "教育；培养",
  effect: "效果；影响；结果",
  effective: "有效的；生效的",
  effort: "努力；艰难的尝试",
  egg: "鸡蛋",
  element: "元素；要素；自然环境",
  else: "其他的；另外的",
  emotional: "情绪的；情感的",
  emphasis: "强调；重点",
  empty: "空的；清空",
  encourage: "鼓励；促进",
  end: "结束；末端；目标",
  ending: "结局；结尾",
  energy: "能量；精力；活力",
  engine: "发动机；引擎",
  engineer: "工程师；策划",
  engineering: "工程学；工程",
  enjoy: "享受；喜爱",
  enough: "足够的；充分的",
  enter: "进入；参加",
  entire: "全部的；整整的",
  environment: "环境；自然环境",
  equal: "平等的；胜任的；等于",
  equipment: "设备；器材",
  escape: "逃跑；逃避",
  especially: "特别；尤其",
  essential: "基本的；必不可少的",
  establish: "建立；确立",
  event: "事件；活动；比赛",
  eventually: "最终；终于",
  everybody: "每个人",
  everyone: "每个人",
  everything: "一切事物；每件事",
  everywhere: "到处；处处",
  evidence: "证据；迹象",
  exact: "精确的；确切的",
  exactly: "精确地；确切地；正是",
  examine: "检查；调查；考试",
  example: "例子；榜样",
  excellent: "极好的；优秀的",
  except: "除了...之外",
  exchange: "交换；交流；兑换",
  exciting: "令人兴奋的",
  exercise: "练习；运动；锻炼",
  exist: "存在；生存",
  existence: "存在；生存",
  expect: "预期；期待；认为",
  expectation: "期望；预期",
  expense: "花费；费用；代价",
  expensive: "昂贵的",
  experience: "经验；经历；体验",
  experiment: "实验；尝试",
  expert: "专家；熟练的",
  explain: "解释；说明",
  explanation: "解释；说明",
  explore: "探索；探究",
  express: "表达；快车；明确的",
  expression: "表达；表情；词语",
  extend: "延伸；扩大；扩展",
  extent: "程度；范围",
  extra: "额外的；特别的",
  extraordinary: "非凡的；特别的",
  eye: "眼睛；眼光",
  face: "脸；面对；表面",
  fact: "事实；真相",
  factor: "因素；要素",
  fail: "失败；未能；衰退",
  failure: "失败；故障",
  fair: "公平的；展销会",
  fairly: "相当地；公平地",
  fall: "落下；下降；秋天",
  familiar: "熟悉的；通俗的",
  family: "家庭；家族",
  famous: "著名的；出名的",
  fan: "粉丝；风扇",
  far: "遥远的；久远的",
  farm: "农场；务农",
  farmer: "农民；农场主",
  fast: "快速的；紧紧地",
  father: "父亲",
  fear: "害怕；恐惧",
  feature: "特征；特色；专题",
  feed: "喂养；提供；饲料",
  feel: "感觉；觉得；触摸",
  feeling: "感觉；情感",
  few: "很少的；几个",
  field: "田野；领域；场地",
  fight: "打架；战斗；争吵",
  figure: "数字；人物；身材；认为",
  fill: "充满；填满",
  film: "电影；胶片",
  final: "最终的；决赛",
  finally: "最后；终于",
  financial: "财务的；金融的",
  find: "找到；发现；感到",
  fine: "美好的；细微的；罚款",
  finger: "手指",
  finish: "完成；结束",
  fire: "火；开火；解雇",
  firm: "坚固的；公司",
  first: "第一；首先",
  fish: "鱼；钓鱼",
  fit: "适合；健康；发作",
  fix: "修理；固定；安装",
  flag: "旗帜",
  flat: "平坦的；公寓",
  flight: "飞行；航班",
  float: "漂浮；浮动",
  flood: "洪水；淹没",
  floor: "地板；楼层",
  flow: "流动；流程",
  flower: "花；开花",
  fly: "飞；苍蝇",
  focus: "焦点；集中",
  follow: "跟随；遵循；理解",
  food: "食物；食品",
  fool: "愚蠢的；傻瓜；欺骗",
  foot: "脚；英尺",
  force: "力量；武力；迫使",
  foreign: "外国的；外来的",
  forest: "森林",
  forget: "忘记；忽略",
  form: "形式；表格；形成",
  formal: "正式的；形式上的",
  former: "以前的；前者",
  forward: "向前；向前看",
  free: "免费的；自由的；释放",
  freedom: "自由",
  freeze: "结冰；冻结",
  frequent: "频繁的；经常的",
  fresh: "新鲜的；清新的",
  friend: "朋友",
  friendly: "友好的",
  friendship: "友谊；友好",
  frighten: "惊吓；恐吓",
  from: "来自；从",
  front: "前面；前线",
  fruit: "水果；果实",
  fuel: "燃料；给...加燃料",
  full: "满的；充满的",
  fully: "完全地；充分地",
  fun: "乐趣；有趣的",
  function: "功能；起作用；宴会",
  fundamental: "基本的；根本的",
  fund: "资金；基金；资助",
  future: "未来；将来的",
  gain: "获得；增加；收益",
  game: "游戏；比赛",
  gap: "差距；缝隙；缺口",
  garden: "花园；菜园",
  gas: "气体；汽油",
  gather: "聚集；收集",
  general: "普遍的；总的；将军",
  generally: "通常；一般而言",
  generate: "产生；发（电）",
  generation: "代；一代人；产生",
  gentle: "温和的；轻柔的",
  gently: "温和地；轻柔地",
  get: "得到；到达；变得",
  gift: "礼物；天赋",
  girl: "女孩",
  give: "给予；提供；付出",
  glad: "高兴的；乐意的",
  glass: "玻璃；玻璃杯；眼镜",
  global: "全球的；整体的",
  go: "去；行走；变为",
  goal: "目标；球门；得分",
  god: "神；上帝",
  gold: "黄金；金色的",
  good: "好的；优良的；商品",
  government: "政府；治理",
  gradual: "渐进的；缓慢的",
  gradually: "逐渐地；渐渐地",
  grain: "粮食；颗粒",
  grand: "宏伟的；重大的",
  grass: "草；草地",
  great: "伟大的；巨大的；极好的",
  greatly: "大大地；极大地",
  green: "绿色的；环保的",
  ground: "地面；土地；根据",
  group: "组；群体；聚集",
  grow: "生长；种植；变得",
  growth: "增长；生长；发展",
  guard: "保卫；看守；警卫",
  guess: "猜测；推测",
  guest: "客人；宾客",
  guide: "引导；指南；导游",
  habit: "习惯；习性",
  hair: "头发；毛发",
  half: "一半；半数",
  hall: "大厅；礼堂",
  hand: "手；递给；帮助",
  handle: "处理；手柄；拿",
  happen: "发生；碰巧",
  happy: "高兴的；幸福的",
  hard: "努力地；坚硬的；困难的",
  hardly: "几乎不；简直不",
  harm: "伤害；损害",
  hat: "帽子",
  hate: "讨厌；憎恨",
  have: "有；拥有",
  head: "头部；率领；朝...行进",
  health: "健康；卫生",
  healthy: "健康的；有益健康的",
  hear: "听见；听说",
  heart: "心脏；内心；核心",
  heat: "热；加热；高潮",
  heavy: "沉重的；繁重的",
  height: "高度；身高",
  help: "帮助；援助",
  helpful: "有帮助的；有益的",
  hide: "隐藏；躲藏",
  high: "高的；高级的",
  highly: "高度地；非常",
  hill: "小山；丘陵",
  history: "历史；历史学",
  hit: "打击；碰撞；击中",
  hold: "握住；容纳；举行",
  hole: "洞；孔",
  holiday: "节日；假期",
  home: "家；家庭",
  honest: "诚实的；正直的",
  hope: "希望；期望",
  horse: "马",
  hospital: "医院",
  hot: "热的；辣的；热门的",
  hotel: "酒店；旅馆",
  hour: "小时；时间",
  house: "房屋；住宅",
  household: "家庭；户",
  how: "怎样；如何",
  however: "然而；无论如何",
  huge: "巨大的；庞大的",
  human: "人类的；人",
  humor: "幽默；诙谐",
  hundred: "百；许多",
  hung: "悬挂（hang过去式）",
  hungry: "饥饿的；渴望的",
  hunt: "打猎；寻找",
  hurry: "赶紧；匆忙",
  hurt: "伤害；疼痛",
  husband: "丈夫",
  ice: "冰；冰镇",
  idea: "想法；主意；概念",
  ideal: "理想的；完美的",
  identical: "完全相同的",
  identify: "识别；鉴定；认同",
  ignore: "忽视；不理睬",
  illness: "疾病；生病",
  image: "图像；形象；印象",
  imagination: "想象力；幻想",
  imagine: "想象；设想",
  impact: "冲击；影响",
  important: "重要的；重大的",
  importance: "重要性",
  impossible: "不可能的",
  impress: "给...留下深刻印象",
  impression: "印象；感想",
  improve: "改进；改善",
  improvement: "改进；提高",
  include: "包括；包含",
  including: "包括...在内",
  income: "收入；收益",
  increase: "增加；增长",
  increasingly: "日益；越来越多地",
  indeed: "的确；甚至",
  independent: "独立的；自主的",
  indicate: "指示；表明",
  individual: "个人的；个体",
  industry: "工业；行业；勤奋",
  influence: "影响；作用",
  inform: "通知；告知",
  information: "信息；资料",
  initial: "最初的；首字母",
  injury: "伤害；负伤",
  inner: "内部的；内心的",
  inside: "在...里面；内部",
  insist: "坚持；坚决要求",
  inspire: "鼓舞；启发",
  instance: "实例；例子",
  instead: "代替；反而",
  instruction: "指令；说明；指导",
  instrument: "乐器；仪器；工具",
  intend: "打算；意图",
  intention: "意图；目的",
  interest: "兴趣；利益；利息",
  interesting: "有趣的；引人入胜的",
  internal: "内部的；国内的",
  international: "国际的",
  interpret: "诠释；口译",
  interrupt: "打扰；中断",
  introduce: "介绍；引进",
  introduction: "介绍；引言",
  invent: "发明；创造",
  invention: "发明；创造",
  invest: "投资；投入",
  investigate: "调查；审查",
  invitation: "邀请；请柬",
  invite: "邀请；招致",
  involve: "包含；涉及；使参与",
  island: "岛屿",
  issue: "问题；发行；期号",
  item: "物品；项目；条款",
  job: "工作；职业",
  join: "加入；连接；结合",
  journey: "旅程；旅行",
  joy: "喜悦；快乐",
  judge: "法官；裁判；判断",
  judgment: "判断；判决",
  jump: "跳跃；暴涨",
  just: "仅仅；刚才；公正的",
  justice: "正义；公正",
  keep: "保持；保存；继续",
  key: "钥匙；关键的；按键",
  kick: "踢；反冲",
  kid: "小孩；开玩笑",
  kill: "杀死；破坏",
  kind: "种类；亲切的",
  king: "国王",
  kitchen: "厨房",
  knee: "膝盖",
  knife: "刀",
  knock: "敲击；打翻",
  know: "知道；了解；认识",
  knowledge: "知识；学问",
  label: "标签；标记",
  labor: "劳动；劳工",
  lack: "缺乏；不足",
  lady: "女士；夫人",
  lake: "湖泊",
  land: "陆地；土地；降落",
  landscape: "风景；地貌",
  language: "语言；话语",
  large: "巨大的；大量的",
  largely: "主要地；很大程度上",
  last: "最后的；持续",
  late: "迟的；晚期的",
  later: "后来；随后",
  latest: "最新的；最近的",
  laugh: "笑；发笑",
  launch: "发射；发起；推出",
  law: "法律；规律",
  lawyer: "律师",
  lay: "放置；铺设；产卵",
  layer: "层；层次",
  lead: "领导；导致；铅",
  leader: "领导者；首领",
  leadership: "领导力；领导层",
  leaf: "树叶；页",
  lean: "倾斜；依靠；瘦的",
  learn: "学习；听说；得知",
  least: "最少的；最少",
  leave: "离开；留下；假期",
  left: "左边的；剩下的",
  leg: "腿",
  legal: "法律的；合法的",
  lesson: "教训；课程",
  let: "让；允许",
  letter: "信件；字母",
  level: "水平；级别；平坦的",
  library: "图书馆",
  lie: "躺；位于；说谎",
  life: "生活；生命",
  lift: "举起；电梯；升力",
  light: "光；明亮的；轻的；点燃",
  like: "喜欢；像...一样",
  likely: "可能的；大概",
  limit: "限制；极限",
  line: "线；线条；排；台词",
  link: "连接；联系；环节",
  lip: "嘴唇",
  liquid: "液体；液态的",
  list: "列表；清单；列出",
  listen: "倾听；听从",
  listener: "听众",
  little: "小的；很少的",
  live: "生活；居住；活的",
  lively: "活泼的；生动的",
  living: "活着的；生活",
  load: "负载；装载",
  loan: "贷款；借出",
  local: "当地的；局部的",
  location: "位置；地点",
  lock: "锁；锁上",
  logic: "逻辑；理路",
  lonely: "孤独的；寂寞的",
  long: "长的；长久的；渴望",
  look: "看；显得；外观",
  loose: "宽松的；松散的",
  lord: "勋爵；主",
  lose: "失去；输掉；遗失",
  loss: "损失；亏损",
  lot: "许多；场地",
  loud: "大声的；响亮的",
  love: "爱；热爱",
  low: "低的；低廉的",
  lower: "降低；更低的",
  luck: "运气；幸运",
  lucky: "幸运的",
  lunch: "午餐",
  machine: "机器；机械",
  mad: "疯狂的；生气的",
  main: "主要的；首要的",
  mainly: "主要地",
  maintain: "维持；保养；坚持",
  major: "主要的；专业",
  majority: "大多数；过半数",
  make: "制造；使得；赚（钱）",
  male: "男性的；雄性的",
  man: "男人；人类",
  manage: "管理；设法应对",
  management: "管理；经营",
  manager: "经理；管理者",
  manner: "方式；礼貌；举止",
  many: "许多的",
  map: "地图",
  march: "行军；三月",
  mark: "标记；分数；打分",
  market: "市场；营销",
  marriage: "婚姻；结婚",
  marry: "结婚；娶；嫁",
  mass: "大量；质量；群众",
  master: "主人；大师；精通",
  match: "匹配；比赛；火柴",
  material: "材料；物资；物质的",
  math: "数学",
  matter: "事情；物质；要紧",
  maximum: "最大值；最高的",
  may: "也许；可以",
  maybe: "也许；大概",
  meal: "一餐；饭食",
  mean: "意思是；意味着；卑劣的",
  meaning: "意思；含义",
  means: "手段；方法；财产",
  meantime: "同时；在此期间",
  measure: "衡量；测量；措施",
  measurement: "测量；尺寸",
  meat: "肉类",
  mechanical: "机械的",
  medical: "医学的；医疗的",
  medicine: "药物；医学",
  medium: "中等的；媒介",
  meet: "遇见；满足；开会",
  meeting: "会议；集会",
  melt: "融化；熔化",
  member: "成员；会员",
  memory: "记忆；回忆；内存",
  mental: "精神的；心理的",
  mention: "提及；说起",
  menu: "菜单",
  merchant: "商人",
  mere: "仅仅的；只不过",
  merely: "仅仅；只",
  message: "信息；消息",
  metal: "金属",
  method: "方法；条理",
  microbe: "微生物",
  middle: "中间的；中部",
  might: "可能；力量",
  mile: "英里",
  military: "军事的；军队",
  milk: "牛奶",
  mind: "头脑；介意；注意力",
  mine: "我的；矿山；采矿",
  mineral: "矿物；矿物质",
  minor: "较小的；未成年人",
  minute: "分钟；微小的",
  miracle: "奇迹",
  mirror: "镜子；反映",
  miss: "错过；想念；小姐",
  mission: "使命；任务",
  mistake: "错误；误解",
  mix: "混合；融合",
  mixture: "混合物",
  model: "模型；模特；榜样",
  modern: "现代的；时髦的",
  modest: "谦虚的；适度的",
  moisture: "水分；湿度",
  moment: "时刻；瞬间",
  money: "金钱；钱",
  month: "月份",
  mood: "情绪；心情",
  moon: "月亮；月球",
  more: "更多的；更加",
  morning: "早晨；上午",
  most: "最多的；大部分",
  mostly: "主要地；大体上",
  mother: "母亲",
  motion: "运动；手势；提议",
  mountain: "山脉；高山",
  mouse: "老鼠；鼠标",
  mouth: "嘴；入口",
  move: "移动；搬家；感动",
  movement: "运动；活动；移动",
  movie: "电影",
  much: "许多的；极地",
  mud: "泥土；泥浆",
  multiple: "多重地；多样的",
  murder: "谋杀",
  muscle: "肌肉；力量",
  museum: "博物馆",
  music: "音乐",
  musician: "音乐家",
  must: "必须；一定",
  mystery: "神秘；谜",
  mysterious: "神秘的；难解的",
  name: "名字；名称；命名",
  narrow: "狭窄的；缩小",
  nation: "国家；民族",
  national: "国家的；国民的",
  native: "本国的；土著的",
  natural: "自然的；天然的",
  naturally: "自然地；理所当然地",
  nature: "自然；天性；本质",
  near: "近的；靠近",
  nearly: "几乎；差不多",
  necessary: "必要的；必需的",
  neck: "脖子；领口",
  need: "需要；必须",
  negative: "消极的；负面的",
  neighbor: "邻居",
  neighborhood: "街区；邻近地区",
  neither: "两者都不",
  nerve: "神经；勇气",
  nervous: "紧张的；神经质的",
  nest: "鸟窝；巢穴",
  net: "网；净余的",
  network: "网络；网状物",
  never: "从不；决不",
  nevertheless: "然而；尽管如此",
  new: "新的；新鲜的",
  news: "新闻；消息",
  newspaper: "报纸",
  next: "下一个的；紧接着的",
  nice: "美好的；漂亮的",
  night: "夜晚；黑夜",
  nobody: "没有人；无名小卒",
  noise: "噪音；响声",
  none: "没有一个；全无",
  nor: "也不",
  normal: "正常的；标准的",
  normally: "通常地；正常地",
  north: "北方；向北",
  nose: "鼻子；嗅觉",
  note: "笔记；注意；便条",
  nothing: "没有什么；无关紧要的事",
  notice: "注意到；通知；告示",
  novel: "小说；新颖的",
  now: "现在；此时",
  nowadays: "现今；时下",
  number: "数字；数量；号码",
  numerous: "众多的；许多的",
  nurse: "护士；护理",
  nut: "坚果；螺母",
  object: "物体；目标；反对",
  observation: "观察；观测",
  observe: "观察；遵守",
  obtain: "获得；赢得",
  obvious: "明显的；显而易见的",
  obviously: "明显地；显而易见",
  occasion: "场合；时机",
  occasional: "偶尔的",
  occupy: "占据；占领",
  occur: "发生；出现",
  ocean: "海洋",
  odds: "几率；胜算",
  off: "离开；切断",
  offend: "冒犯；得罪",
  offer: "提供；出价；提议",
  office: "办公室；职务",
  officer: "官员；警官",
  official: "官方的；官员",
  often: "经常；常常",
  oil: "石油；食用油",
  old: "古老的；旧的；年老的",
  once: "一次；曾经",
  one: "一个；人",
  online: "在线的；网上的",
  only: "仅仅；唯一的",
  open: "打开；公开的；坦率的",
  operate: "操作；经营；动手术",
  operation: "操作；手术；运转",
  opinion: "意见；看法",
  opportunity: "机会；时机",
  opposite: "相反的；对面的",
  option: "选项；选择",
  or: "或者；否则",
  orange: "橙色的；橘子",
  order: "顺序；命令；订单",
  ordinary: "普通地；平淡的",
  organ: "器官；风琴",
  organism: "生物体；有机体",
  organization: "组织；机构",
  organize: "组织；安排",
  origin: "起源；出身",
  original: "原始的；独创的",
  originally: "最初；本来",
  other: "其他的；另外的",
  otherwise: "否则；在其他方面",
  ought: "应该",
  our: "我们的",
  out: "向外；在外",
  outcome: "结果；产出",
  outside: "在外面；外部",
  over: "越过；超过；结束",
  overall: "全面的；总体地",
  overlook: "俯瞰；忽略",
  owe: "欠；归功于",
  own: "自己的；拥有",
  owner: "主人；所有者",
  oxygen: "氧气",
  pace: "步调；节奏",
  pack: "包裹；打包",
  package: "包裹；套餐",
  page: "页；页面",
  pain: "疼痛；痛苦",
  paint: "绘画；油漆",
  painter: "画家",
  painting: "画作；绘画",
  pair: "一对；一双",
  pale: "苍白的；暗淡的",
  paper: "纸；报纸；论文",
  paragraph: "段落",
  pardon: "原谅；请再说一遍",
  parent: "父母",
  park: "公园；停车",
  part: "部分；零件；角色",
  particular: "特别的；具体的",
  particularly: "特别；尤其",
  partly: "部分地",
  partner: "伙伴；搭档",
  party: "政党；聚会",
  pass: "通过；经过；通行证",
  passage: "通道；文章段落",
  passenger: "乘客；旅客",
  passion: "激情；热情",
  passive: "被动的；消极的",
  past: "过去的；过往",
  path: "小路；路径",
  patience: "耐心；忍耐",
  patient: "病人；有耐心的",
  pattern: "模式；图案",
  pause: "暂停；停顿",
  pay: "支付；工资",
  peace: "和平；平静",
  peaceful: "和平的；宁静的",
  pen: "钢笔",
  pencil: "铅笔",
  people: "人们；民族",
  per: "每；每一",
  perceive: "感知；察觉",
  percent: "百分之...",
  perfect: "完美的；完美的",
  perfectly: "完美地；完全地",
  perform: "执行；表演",
  performance: "表现；表演；性能",
  perhaps: "也许；可能",
  period: "时期；句号",
  permanent: "永久的；固定的",
  permission: "允许；许可",
  permit: "允许；许可证",
  person: "人；个人",
  personal: "个人的；私人的",
  personality: "个性；人格",
  personally: "就个人而言",
  persuade: "说服；劝说",
  pet: "宠物",
  phone: "电话；打电话",
  photo: "照片",
  photograph: "照片；摄影",
  phrase: "短语；词组",
  physical: "身体的；物理的",
  physics: "物理学",
  pick: "挑选；采摘",
  picture: "图片；画面",
  piece: "块；片；件",
  pilot: "飞行员；领航员",
  pin: "大头针；固定",
  pine: "松树；渴望",
  pink: "粉红色的",
  pioneer: "先驱；开拓者",
  pipe: "管道；烟斗",
  pity: "可惜；同情",
  place: "地方；放置；名次",
  plain: "简单的；平原",
  plan: "计划；方案",
  plane: "飞机；平面",
  planet: "行星；地球",
  plant: "植物；工厂；种植",
  plastic: "塑料的；塑料",
  plate: "盘子；板块",
  platform: "平台；讲台",
  play: "玩耍；播放；剧本",
  player: "玩家；选手",
  pleasant: "令人愉快的",
  please: "请；使高兴",
  pleasure: "高兴；乐趣",
  plenty: "丰富；大量",
  plot: "情节；阴谋；小块土地",
  pocket: "口袋",
  poem: "诗歌",
  poet: "诗人",
  poetry: "诗歌",
  point: "要点；得分；指向",
  poison: "毒药；毒害",
  police: "警察；警方",
  policy: "政策；方针",
  polite: "礼貌的",
  political: "政治的",
  politician: "政治家",
  politics: "政治",
  pollution: "污染",
  pool: "水池；水塘",
  poor: "贫穷的；可怜的；差的",
  popular: "受欢迎的；流行的",
  population: "人口；种群",
  port: "港口",
  portion: "部分；一份",
  position: "位置；立场；职位",
  positive: "积极的；正面的；确信的",
  possess: "具备；拥有",
  possibility: "可能性",
  possible: "可能的",
  possibly: "可能地",
  post: "帖子；岗位；邮政；张贴",
  potato: "马铃薯；土豆",
  potential: "潜在的；潜能",
  pound: "磅；英镑；猛击",
  pour: "倾倒；倾泻",
  poverty: "贫困；贫穷",
  powder: "粉末",
  power: "力量；电力；权力",
  powerful: "强大的；有力的",
  practical: "实用的；实际的",
  practice: "练习；实践；惯例",
  praise: "赞美；称赞",
  pray: "祈祷",
  predict: "预测；预言",
  prefer: "更喜欢；宁愿",
  preference: "偏好；优先选择",
  prepare: "准备；预备",
  preparation: "准备；预备",
  presence: "存在；出席",
  present: "呈现；礼物；现在的",
  preserve: "保护；保存",
  president: "总统；主席；总裁",
  press: "按；压；新闻界",
  pressure: "压力；压强",
  pretend: "假装；伪装",
  pretty: "漂亮的；相当",
  prevent: "预防；阻止",
  previous: "以前的；先前的",
  previously: "此前；以前",
  price: "价格；代价",
  pride: "骄傲；自豪",
  priest: "祭司；牧师",
  primary: "主要的；初级的",
  prince: "王子",
  princess: "公主",
  principal: "主要的；校长",
  principle: "原则；原理",
  print: "印刷；打印；字迹",
  printer: "打印机",
  priority: "优先事项",
  prison: "监狱",
  prisoner: "囚犯",
  private: "私人的；私立的",
  prize: "奖品；奖金",
  probable: "可能的",
  probably: "大概；很可能",
  problem: "问题；难题",
  procedure: "程序；步骤",
  process: "过程；处理；加工",
  produce: "生产；产生；农产品",
  producer: "生产者；制片人",
  product: "产品；产物",
  production: "生产；产量",
  profession: "职业；行业",
  professional: "专业的；专业人员",
  professor: "教授",
  profile: "轮廓；简介",
  profit: "利润；收益",
  program: "程序；节目；计划",
  progress: "进步；进展",
  project: "项目；工程；预测",
  promise: "承诺；许诺",
  promote: "促进；推广；晋升",
  pronounce: "发音；宣告",
  proof: "证明；证据",
  proper: "适当的；正确的",
  properly: "合适地；正确地",
  property: "财产；资产；属性",
  proportion: "比例；部分",
  proposal: "提议；建议",
  propose: "提议；建议",
  protect: "保护；保卫",
  protection: "保护",
  protein: "蛋白质",
  protest: "抗议；反对",
  proud: "自豪的；骄傲的",
  prove: "证明；证实",
  provide: "提供；给予",
  provided: "假如；只要",
  public: "公众的；公开的",
  publish: "出版；发表",
  pull: "拉；拖",
  pump: "泵；抽水",
  punish: "惩罚；处罚",
  punishment: "惩罚",
  pupil: "小学生；瞳孔",
  purchase: "购买；采购",
  pure: "纯洁的；纯净的",
  purpose: "目的；意图",
  pursue: "追求；追逐",
  push: "推；推动",
  put: "放置；表达",
  quality: "质量；品质；特质",
  quantity: "数量",
  quarter: "四分之一；一刻钟",
  queen: "女王；王后",
  question: "问题；疑问；询问",
  quick: "快速的；敏捷的",
  quickly: "快速地；迅速",
  quiet: "安静的；平静的",
  quietly: "安静地；悄悄地",
  quite: "相当；十分",
  race: "赛跑；种族",
  radio: "收音机；无线电",
  rail: "铁轨；栏杆",
  railway: "铁路",
  rain: "下雨；雨水",
  rainbow: "彩虹",
  raise: "举起；抚养；提高",
  range: "范围；幅度；山脉",
  rank: "等级；阶级；排名",
  rapid: "快速的；敏捷的",
  rapidly: "迅速地；飞快地",
  rare: "罕见的；稀有的",
  rarely: "很少；罕见地",
  rate: "速率；比率；评价",
  rather: "相当；宁愿",
  ratio: "比例；比率",
  raw: "生的；未加工的",
  reach: "到达；伸出；达成",
  react: "反应；起作用",
  reaction: "反应；反作用",
  read: "阅读；朗读",
  reader: "读者",
  readily: "容易地；乐意地",
  ready: "准备好的；现成的",
  real: "真实的；真正的",
  realistic: "现实的；实际的",
  reality: "现实；实际情况",
  realize: "意识到；实现",
  really: "真正地；确实",
  reason: "原因；理由；理性",
  reasonable: "合理的；适度的",
  recall: "回忆；召回",
  receive: "收到；接收；对待",
  recent: "最近的；近来的",
  recently: "最近；近来",
  recognition: "识别；认可",
  recognize: "认出；承认",
  recommend: "推荐；建议",
  record: "记录；唱片；纪录",
  recover: "恢复；康复",
  recovery: "恢复；复苏",
  red: "红色的；红色",
  reduce: "减少；降低",
  reduction: "减少；缩减",
  refer: "参考；提及；指的是",
  reflect: "反映；反射；深思",
  reflection: "反射；反映；沉思",
  reform: "改革；改善",
  refuse: "拒绝；谢绝",
  regard: "看待；把...看作；问候",
  regarding: "关于",
  regardless: "不管；不顾",
  region: "地区；区域",
  regional: "地区的；区域的",
  register: "注册；登记",
  regret: "遗憾；后悔",
  regular: "规律的；定期地",
  regularly: "定期地；有规律地",
  regulation: "规则；规章；调节",
  reject: "拒绝；排斥",
  relate: "联系；有关",
  related: "相关的；有亲戚关系的",
  relation: "关系；联系",
  relationship: "关系；关联",
  relative: "相对的；亲戚",
  relatively: "相对地；比较而言",
  relax: "放松；休息",
  release: "释放；发布",
  relevant: "相关的；切题的",
  reliable: "可靠的；可信赖的",
  relief: "宽慰；轻松；救济",
  religion: "宗教",
  rely: "依赖；依靠",
  remain: "保持；仍是；留下",
  remaining: "剩下的",
  remains: "残余；遗迹",
  remark: "备注；评论",
  remarkable: "非凡的；卓越的",
  remarkably: "显著地；非凡地",
  remember: "记得；记住",
  remind: "提醒；使想起",
  remote: "偏远的；遥远的",
  remove: "移开；去除",
  rent: "租金；出租",
  repair: "修理；修补",
  repeat: "重复；重说",
  replace: "替换；取代",
  reply: "回复；回答",
  report: "报告；报道",
  reporter: "记者",
  represent: "代表；表现",
  reputation: "声誉；名声",
  request: "请求；要求",
  require: "需要；要求",
  requirement: "要求；必要条件",
  research: "研究；调查",
  researcher: "研究人员",
  reserve: "储备；预订；保留",
  resident: "居民；常住的",
  resist: "抵抗；抵制",
  resistance: "阻力；抵抗",
  resolution: "分辨率；决心；解决",
  resolve: "解决；决定",
  resort: "度假胜地；诉诸",
  resource: "资源；财力",
  respect: "尊重；敬佩；方面",
  respond: "回应；回答",
  response: "回应；反应",
  responsibility: "责任；职责",
  responsible: "有责任的；负责的",
  rest: "休息；其余部分",
  restaurant: "餐厅；饭店",
  result: "结果；产生",
  retail: "零售",
  retain: "保留；保持",
  retire: "退休",
  return: "返回；归还；回报",
  reveal: "揭示；透露",
  revenues: "收入；税收",
  reverse: "颠倒；反转；相反的",
  review: "复习；审查；评论",
  revolution: "革命；旋转",
  reward: "奖励；报酬",
  rhythm: "节奏；韵律",
  rice: "米饭；大米",
  rich: "富有地；丰富的",
  rid: "使摆脱；使去掉",
  ride: "骑；乘；搭便车",
  right: "正确的；右边的；权利",
  ring: "戒指；环；打电话",
  rise: "上升；上涨；增加",
  risk: "风险；冒...风险",
  rival: "竞争对手",
  river: "河流",
  road: "道路；公路",
  rob: "抢劫；盗窃",
  robot: "机器人",
  rock: "岩石；摇滚乐",
  rod: "杆；棒",
  role: "角色；作用",
  roll: "滚动；卷",
  roof: "屋顶",
  room: "房间；空间",
  root: "根；根源",
  rope: "绳子",
  rough: "粗糙的；大致的",
  roughly: "大致地；粗略地",
  round: "圆的；围绕；一轮",
  route: "路线；路途",
  routine: "常规；日常事务",
  row: "行；排；划船",
  royal: "皇家的；王室的",
  rub: "摩擦；涂抹",
  rubber: "橡胶",
  ruin: "毁坏；废墟",
  rule: "规则；统治；裁决",
  ruler: "统治者；直尺",
  rumor: "谣言；传闻",
  run: "跑；运行；经营",
  runner: "跑步者",
  running: "跑步；运转",
  rural: "乡村的；农村的",
  rush: "冲；奔；仓促",
  sad: "悲伤的",
  safe: "安全的；保险箱",
  safety: "安全；安全性",
  sail: "航行；帆",
  sailor: "水手",
  sake: "缘故；利益",
  salad: "沙拉",
  salary: "薪水",
  sale: "销售；拍卖",
  sales: "销售额",
  salt: "盐",
  same: "相同的；同样的事物",
  sample: "样品；样本",
  sand: "沙子；沙滩",
  satisfy: "满足；使满意",
  save: "拯救；储蓄；节省",
  saving: "节省；储蓄",
  say: "说；讲；例如",
  scale: "规模；天平；鳞片",
  scene: "场景；现场",
  schedule: "时间表；日程",
  scheme: "方案；计划",
  scholar: "学者",
  school: "学校；学派",
  science: "科学",
  scientific: "科学的",
  scientist: "科学家",
  score: "得分；分数",
  scream: "尖叫",
  screen: "屏幕；屏风",
  sea: "大海；海洋",
  search: "搜索；寻找",
  season: "季节；赛季",
  seat: "座位；使坐下",
  second: "秒；第二的",
  secondary: "次要的；中等的",
  secret: "秘密；秘诀",
  secretary: "秘书",
  section: "章节；部分",
  sector: "部门；领域",
  secure: "安全的；稳妥地",
  security: "安全；保卫",
  see: "看见；理解；参观",
  seed: "种子",
  seek: "寻找；寻求",
  seem: "似乎；像是",
  seemingly: "看似地；表面上",
  seldom: "很少；罕见",
  select: "挑选；选择",
  selection: "选择；挑选出来的东西",
  self: "自我；自己",
  sell: "卖；销售",
  seller: "卖家",
  send: "发送；寄出",
  senior: "资深的；高级的",
  sense: "感觉；理智；含义",
  sensitive: "敏感的；体贴的",
  sentence: "句子；判决",
  separate: "分开的；单独的",
  series: "系列；连续",
  serious: "严肃的；严重的",
  seriously: "严肃地；认真地",
  servant: "仆人",
  serve: "服务；服役；招待",
  service: "服务；公共机构",
  session: "会议；学期",
  set: "设置；放置；一套",
  setting: "背景；设置",
  settle: "解决；安顿",
  settlement: "解决；定居点",
  several: "几个；数个",
  severe: "严重的；严厉的",
  sew: "缝纫；缝补",
  shade: "树荫；阴影；色调",
  shadow: "影子；阴影",
  shake: "摇晃；震动",
  shall: "将要；应该",
  shallow: "浅的；肤浅的",
  shame: "羞耻；遗憾的事",
  shape: "形状；塑造",
  share: "分享；股份；份额",
  sharp: "锋利的；敏锐的；剧烈的",
  sharply: "急剧地；锐利地",
  she: "她",
  sheep: "羊；绵羊",
  sheet: "床单；纸张；薄板",
  shelf: "搁板；书架",
  shell: "贝壳；壳",
  shelter: "庇护所；遮蔽",
  shift: "转移；转变；轮班",
  shine: "发光；照耀",
  ship: "船；运送",
  shirt: "衬衫",
  shock: "震惊；震动",
  shoe: "鞋子",
  shoot: "射击；拍摄；发芽",
  shop: "商店；购物",
  shopper: "购物者",
  shopping: "购物",
  shore: "岸；滨",
  short: "短的；简短的；矮的",
  shortage: "短缺；不足",
  shortly: "不久；很快",
  shot: "射击；照片；尝试",
  should: "应该；应当",
  shoulder: "肩膀",
  shout: "呼喊；大叫",
  show: "展示；表明；演出",
  shower: "淋浴；阵雨",
  shut: "关上；关闭",
  shy: "害羞的",
  sick: "生病的；恶心的",
  side: "侧面；边缘；一方",
  sight: "视力；景象；看见",
  sign: "标志；符号；签署",
  signal: "信号；发信号",
  signature: "签名",
  significance: "重要性；意义",
  significant: "显著的；重要的",
  significantly: "显著地；相当大程度上",
  silence: "沉默；寂静",
  silent: "沉默的；寂静的",
  silk: "丝绸",
  silly: "傻的；愚蠢的",
  silver: "银；银色的",
  similar: "相似的；类似的",
  similarly: "同样地；类似地",
  simple: "简单的；朴素的",
  simply: "仅仅；简单地",
  since: "自...以来；因为",
  sincere: "真诚的；诚挚的",
  sing: "唱歌",
  singer: "歌手",
  single: "单一的；单身的",
  sink: "下沉；水槽",
  sir: "先生；阁下",
  sister: "姐妹",
  sit: "坐；位于",
  site: "地点；场所；网站",
  situation: "情况；局势",
  size: "大小；尺寸",
  skill: "技能；技巧",
  skin: "皮肤；皮",
  skirt: "裙子",
  sky: "天空",
  slave: "奴隶",
  sleep: "睡眠；睡觉",
  slight: "轻微的；微小的",
  slightly: "轻微地；稍微",
  slip: "滑倒；滑落；纸条",
  slow: "放慢；减速；缓慢的",
  slowly: "缓慢地",
  small: "小的；微小的",
  smart: "聪明的；敏捷的",
  smell: "气味；闻到",
  smile: "微笑",
  smoke: "烟；吸烟",
  smooth: "光滑的；平稳的",
  smoothly: "平稳地；顺利地",
  snake: "蛇",
  snow: "雪；下雪",
  so: "所以；如此",
  social: "社会的；社交的",
  society: "社会；社团",
  soft: "柔软的；柔和的",
  softly: "轻柔地",
  soil: "土壤；泥土",
  solar: "太阳的",
  soldier: "士兵；军人",
  solid: "固体的；坚固的",
  solution: "解决方案；溶液",
  solve: "解决；解答",
  some: "一些；某些",
  somebody: "有人；某人",
  somehow: "以某种方式；不知怎么地",
  someone: "某人",
  something: "某物；某事",
  sometime: "某个时候",
  sometimes: "有时；偶尔",
  somewhat: "稍微；有点",
  somewhere: "在某处",
  son: "儿子",
  song: "歌曲",
  soon: "不久；很快",
  sorry: "抱歉的；遗憾的",
  sort: "种类；整理；分类",
  soul: "灵魂；心灵",
  sound: "声音；听起来；健全的",
  source: "来源；源头",
  south: "南方；向南",
  space: "空间；太空",
  spare: "备用的；空闲的",
  speak: "说话；演讲",
  speaker: "说话者；演讲者；扬声器",
  special: "特别的；专门的",
  species: "物种；种类",
  specific: "具体的；特定的",
  specifically: "具体地；专门地",
  speech: "演讲；言语",
  speed: "速度；加速",
  spell: "拼写；符咒",
  spend: "花费；度过",
  spirit: "精神；灵魂",
  spite: "恶意；怨恨",
  splendid: "壮丽的；极好的",
  split: "分裂；拆分",
  spoil: "破坏；宠坏",
  sport: "运动；体育",
  spot: "地点；斑点；发现",
  spread: "传播；展开；散布",
  spring: "春天；泉水；弹簧",
  square: "广场；正方形",
  stable: "稳定的；马厩",
  staff: "工作人员；员工",
  stage: "阶段；舞台",
  stair: "楼梯",
  stamp: "邮票；盖印",
  stand: "站立；忍受；看台",
  standard: "标准；规格",
  star: "星星；明星",
  stare: "盯着看；凝视",
  start: "开始；出发",
  state: "状态；国家；州；陈述",
  statement: "声明；陈述",
  station: "车站；局；驻扎",
  status: "状态；地位",
  stay: "停留；保持",
  steady: "平稳的；稳固的",
  steal: "偷窃",
  steam: "蒸汽",
  steel: "钢铁",
  steep: "陡峭的",
  step: "脚步；步骤；迈步",
  stick: "棍棒；粘贴",
  stiff: "硬的；僵硬的",
  still: "仍然；静止的",
  stimulate: "刺激；激励",
  stomach: "胃；肚子",
  stone: "石头",
  stop: "停止；车站",
  storage: "存储；储藏",
  store: "商店；储存",
  storm: "暴风雨",
  story: "故事；新闻报道",
  straight: "笔直的；直接",
  strange: "奇怪的；陌生的",
  stranger: "陌生人",
  strategy: "策略；战略",
  stream: "溪流；小河；流动",
  street: "街道",
  strength: "力量；长处",
  strengthen: "加强；巩固",
  stress: "压力；强调",
  stretch: "拉伸；延伸",
  strict: "严格的；严厉的",
  strike: "击打；罢工；撞击",
  string: "细绳；一串",
  strip: "剥去；条；带",
  strong: "强壮的；强大的",
  strongly: "强烈地",
  structure: "结构；建筑物",
  struggle: "挣扎；奋斗",
  student: "学生",
  studio: "工作室；演播室",
  study: "学习；研究；书房",
  stuff: "东西；材料",
  stupid: "愚蠢的",
  style: "风格；款式",
  subject: "主题；科目；受制于",
  substance: "物质；实质",
  substantial: "大量的；实质的",
  succeed: "成功；继承",
  success: "成功",
  successful: "成功的",
  successfully: "成功地",
  such: "这样的；如此的",
  sudden: "突然地；意外地",
  suddenly: "突然间",
  suffer: "遭受；忍受",
  sufficient: "充分的；足够的",
  sugar: "糖",
  suggest: "建议；暗示",
  suggestion: "建议；提议",
  suit: "适合；西装",
  suitable: "合适的；适当的",
  sum: "总数；金额",
  summary: "摘要；总结",
  summer: "夏天",
  sun: "太阳",
  sunlight: "阳光",
  sunny: "阳光明媚的",
  sunrise: "日出",
  sunset: "日落",
  super: "超级的",
  supermarket: "超市",
  supper: "晚餐",
  supply: "供应；补给",
  support: "支持；支撑；抚养",
  suppose: "假设；认为",
  supposed: "应当的；被假定的",
  sure: "确信地；当然",
  surely: "无疑；必定",
  surface: "表面；地表",
  surprise: "惊奇；使惊讶",
  surprised: "感到惊讶的",
  surprising: "令人惊讶的",
  surprisingly: "出人意料地",
  surround: "包围；围绕",
  surrounding: "周围的",
  survey: "调查；测量",
  survival: "生存；幸存",
  survive: "幸存；活下来",
  suspect: "怀疑；犯罪嫌疑人",
  sustain: "维持；支撑",
  sustainable: "可持续的",
  sweet: "甜的；可爱的",
  swim: "游泳",
  symbol: "符号；象征",
  system: "系统；体系；制度",
  table: "桌子；表格",
  tail: "尾巴",
  take: "拿；拿走；花费；乘坐",
  tale: "传说；故事",
  talent: "天才；才能",
  talk: "谈话；演讲",
  tall: "高的",
  task: "任务；工作",
  taste: "品尝；味道；品味",
  tax: "税收",
  tea: "茶",
  teach: "教；教授",
  teacher: "教师",
  teaching: "教学",
  team: "团队",
  tear: "眼泪；撕裂",
  technical: "技术的；专业的",
  technique: "技巧；技术",
  technology: "技术；科技",
  tell: "告诉；讲述；辨别",
  temperature: "温度",
  temporary: "暂时的；临时的",
  tend: "倾向于；照顾",
  tendency: "倾向；趋势",
  tender: "温柔的；温柔地",
  term: "术语；学期；条款",
  terrible: "可怕地；糟糕的",
  test: "测试；试验",
  text: "文本；正文",
  than: "比",
  thank: "感谢",
  thanks: "感谢；多亏",
  that: "那个；那",
  theater: "剧院",
  theme: "主题",
  then: "那时；然后",
  theory: "理论；学说",
  there: "那里",
  therefore: "因此；所以",
  thick: "厚的；浓的",
  thin: "薄的；瘦的",
  thing: "东西；事情",
  think: "想；认为；思考",
  thinking: "思考；想法",
  third: "第三的；三分之一",
  thirty: "三十",
  this: "这个",
  thorough: "彻底地；详尽地",
  though: "虽然；不过",
  thought: "想法；思考；想（think过去式）",
  thousand: "千；成千上万",
  threat: "威胁；恐吓",
  threaten: "威胁",
  three: "三",
  threshold: "门槛；阈值",
  through: "穿过；通过",
  throughout: "贯穿；自始至终",
  throw: "扔；投掷",
  thrust: "推力；刺",
  thus: "因此；从而",
  ticket: "票；车票",
  tide: "潮汐；潮流",
  tie: "系；绑；领带；平局",
  tight: "紧的；紧密地",
  till: "直到...为止",
  time: "时间；次数；时代",
  tiny: "微小的；极小的",
  tip: "小费；技巧；尖端",
  tire: "轮胎；疲劳",
  tired: "疲倦的；厌烦的",
  tissue: "组织；面巾纸",
  title: "标题；头衔",
  to: "向；到",
  today: "今天；当今",
  together: "一起；共同",
  tomorrow: "明天",
  tonight: "今晚",
  too: "也；太",
  tool: "工具；手段",
  tooth: "牙齿",
  top: "顶部；顶级的",
  topic: "话题；主题",
  total: "总的；总数",
  totally: "完全地；整整",
  touch: "触摸；接触；感动",
  tough: "艰难的；强硬的",
  tour: "旅游；巡回",
  tourist: "游客",
  toward: "朝向；对于",
  towards: "朝向",
  tower: "塔；高楼",
  town: "城镇",
  toy: "玩具",
  trace: "追踪；痕迹",
  track: "轨道；小路；追踪",
  trade: "贸易；交易",
  tradition: "传统",
  traditional: "传统的",
  traffic: "交通；流量",
  trail: "小径；痕迹",
  train: "火车；训练",
  training: "训练；培训",
  transfer: "转移；转账",
  transform: "改变；转换",
  translate: "翻译；转化",
  translation: "翻译；译文",
  transport: "运输；交通工具",
  travel: "旅行；移动",
  traveler: "旅行者",
  treasure: "宝藏；珍惜",
  treat: "对待；治疗；款待",
  treatment: "对待；治疗",
  tree: "树木",
  trend: "趋势；倾向",
  trial: "审判；试验",
  tribe: "部落",
  trick: "戏法；诀窍；欺骗",
  trip: "旅行；绊倒",
  triumph: "胜利；成功",
  trouble: "麻烦；困难",
  truck: "卡车",
  true: "真实的；真正的",
  truly: "真实地；确实",
  trust: "信任；信赖",
  truth: "真理；真相",
  try: "尝试；努力",
  tube: "管子；地铁",
  turn: "旋转；转弯；变为；轮流",
  tv: "电视",
  twelve: "十二",
  twenty: "二十",
  twice: "两次；两倍",
  twin: "双胞胎",
  twist: "扭曲；盘旋",
  two: "二",
  type: "类型；打字",
  typical: "典型的；特有的",
  typically: "典型地；通常",
  ugly: "丑陋的",
  ultimate: "最终的；极限的",
  ultimately: "最终地",
  unable: "无法...的；不能的",
  uncertain: "不确定的",
  uncle: "叔叔；伯伯；舅舅",
  unclear: "不清楚的",
  uncomfortable: "不舒服的",
  unconscious: "无意识的",
  under: "在...下面",
  undergo: "经历；经受",
  underground: "地下的；地下铁",
  understand: "理解；懂得",
  understanding: "理解；谅解",
  undertake: "承担；从事",
  undoubtedly: "毫无疑问地",
  unfortunate: "不幸的",
  unfortunately: "不幸的是",
  unhappy: "不高兴的",
  uniform: "制服；统一的",
  union: "工会；结合；联盟",
  unique: "独特的；唯一的",
  unit: "单元；单位",
  unite: "团结；联合",
  united: "联合的；团结的",
  unity: "团结；统一",
  universal: "普遍的；通用的",
  universe: "宇宙",
  university: "大学",
  unknown: "未知的；无名的",
  unless: "除非",
  unlike: "不像；与...不同",
  unlikely: "不大可能的",
  unusual: "不寻常的；独特的",
  unusually: "不寻常地；极其",
  up: "向上",
  upon: "在...之上",
  upper: "较高的；上层的",
  upset: "使心烦；弄翻",
  upstairs: "在楼上",
  urban: "城市的",
  urge: "催促；强烈欲望",
  urgent: "紧急的；迫切的",
  use: "使用；利用；用途",
  used: "习惯的；用过的",
  useful: "有用的；有益的",
  useless: "无用的",
  user: "用户",
  usual: "通常的；惯常的",
  usually: "通常地",
  valley: "山谷；流域",
  valuable: "贵重的；有价值的",
  value: "价值；重视",
  variety: "多样；种类",
  various: "各种各样的",
  vary: "变化；不同",
  vast: "巨大的；辽阔的",
  vegetable: "蔬菜",
  vegetation: "植被",
  vehicle: "车辆；交通工具",
  version: "版本；说法",
  very: "非常；很",
  vessel: "船只；血管",
  victim: "受害者",
  victory: "胜利",
  video: "视频",
  view: "观点；视图；风景；看待",
  viewer: "观众",
  village: "村庄",
  violence: "暴力",
  violent: "暴力的",
  virtual: "虚拟的；实质上的",
  virtually: "实际上；几乎",
  virtue: "美德；优点",
  virus: "病毒",
  visible: "看得见的；显眼的",
  vision: "视力；视觉；远见",
  visit: "访问；参观",
  visitor: "访问者；游客",
  visual: "视觉的",
  vital: "至关重要的；有活力的",
  voice: "声音；嗓音；表达",
  volume: "体积；音量；卷",
  voluntary: "志愿的；自愿的",
  vote: "投票；选票",
  voyage: "航海；航行",
  wage: "工资",
  wait: "等待",
  waiter: "服务员",
  wake: "醒来；唤醒",
  walk: "走路；散步；步行",
  wall: "墙壁",
  wander: "漫步；游荡；迷路",
  want: "想要；需要",
  war: "战争",
  warm: "温暖的；热情的",
  warn: "警告；提醒",
  warning: "警告；预兆",
  wash: "洗涤；洗",
  waste: "浪费；废品；荒芜的",
  watch: "观看；看守；手表",
  water: "水；浇水",
  wave: "波浪；挥手",
  wavelength: "波长",
  way: "道路；方法；方向；程度",
  weak: "软弱的；虚弱的",
  weakness: "弱点；软弱",
  wealth: "财富；丰富",
  weapon: "武器",
  wear: "穿；戴；磨损",
  weather: "天气",
  web: "网；网络",
  wedding: "婚礼",
  week: "星期；周",
  weekend: "周末",
  weekly: "每周的",
  weigh: "称重；权衡",
  weight: "重量；重物",
  welcome: "欢迎",
  well: "好地；健康的；井",
  west: "西方；向西",
  western: "西方的",
  wet: "湿的",
  what: "什么",
  whatever: "无论什么",
  wheel: "车轮；轮子",
  when: "当...时",
  whenever: "无论何时",
  where: "在哪里",
  wherever: "无论哪里",
  whether: "是否",
  which: "哪一个",
  whichever: "无论哪个",
  while: "当...时；然而",
  whisper: "低语；耳语",
  white: "白色的；白色",
  who: "谁",
  whoever: "无论是谁",
  whole: "全部地；整体",
  wholly: "完全地；整整",
  whom: "谁（宾格）",
  whose: "谁的",
  why: "为什么",
  wide: "宽广的；广泛地",
  widely: "广泛地",
  widespread: "广泛的；普遍的",
  wife: "妻子",
  wild: "野生地的；狂野的",
  wildlife: "野生动物",
  will: "将；会；意志；遗嘱",
  willing: "乐意的；自愿的",
  win: "获胜；赢得",
  window: "窗户",
  wing: "机翼；翅膀",
  winner: "赢家；胜利者",
  winter: "冬天",
  wipe: "擦拭；擦去",
  wire: "金属丝；电线",
  wisdom: "智慧；明智",
  wise: "明智的；聪明的",
  wish: "希望；祝愿",
  with: "和...在一起；用",
  withdraw: "撤回；提取（钱）",
  within: "在...之内",
  without: "没有；无",
  witness: "目击者；见证",
  woman: "女人",
  wonder: "想知道；奇迹",
  wonderful: "极好的；精彩的",
  wood: "木头；树林",
  wooden: "木制的",
  word: "单词；话语",
  work: "工作；起作用；作品",
  worker: "工人；工作者",
  working: "工作的；运转的",
  world: "世界；地球",
  worldwide: "全世界的",
  worried: "担心的；发愁的",
  worry: "担心；发愁",
  worse: "更差地；更坏的",
  worship: "崇拜；敬奉",
  worst: "最差地；最坏的",
  worth: "值得的；价值",
  worthwhile: "值得做的",
  would: "将会；总是；愿意",
  wound: "伤口；伤害",
  wrap: "包裹；缠绕",
  write: "写；写作",
  writer: "作家；作者",
  writing: "写作；文章",
  written: "书面的；写下的",
  wrong: "错误的；不道德的",
  yard: "院子；码",
  year: "年份；年",
  yawn: "打哈欠",
  yellow: "黄色的",
  yes: "是的",
  yesterday: "昨天",
  yet: "然而；还；已经",
  yield: "产生；屈服；产量",
  young: "年轻的；幼小的",
  youth: "青年；青春",
  zero: "零；零点",
  zone: "区域；地带"
};

const IRREGULAR_LEMMAS = {
  went: "go",
  gone: "go",
  done: "do",
  did: "do",
  seen: "see",
  saw: "see",
  taken: "take",
  took: "take",
  made: "make",
  thought: "think",
  brought: "bring",
  bought: "buy",
  felt: "feel",
  found: "find",
  kept: "keep",
  left: "leave",
  known: "know",
  knew: "know",
  written: "write",
  wrote: "write",
  built: "build",
  spent: "spend",
  sent: "send",
  held: "hold",
  led: "lead",
  lost: "lose",
  meant: "mean",
  met: "meet",
  paid: "pay",
  said: "say",
  sold: "sell",
  told: "tell",
  caught: "catch",
  taught: "teach",
  driven: "drive",
  drove: "drive",
  given: "give",
  gave: "give",
  chosen: "choose",
  chose: "choose",
  spoken: "speak",
  spoke: "speak",
  broken: "break",
  broke: "break",
  grown: "grow",
  grew: "grow",
  flown: "fly",
  flew: "fly",
  drawn: "draw",
  drew: "draw",
  shown: "show",
  begun: "begin",
  began: "begin",
  ran: "run",
  became: "become",
  came: "come",
  children: "child",
  people: "person",
  feet: "foot",
  teeth: "tooth",
  mice: "mouse",
  men: "man",
  women: "woman",
  worse: "bad",
  worst: "bad"
};

const GLOBAL_MEANING_INDEX = buildGlobalMeaningIndex(chapters);

function getChapterWords(chapter) {
  return chapter.words.map(item => ({ ...item, isPreset: true }));
}
function normalizeWord(word) {
  return String(word || "").toLowerCase().trim();
}
function buildGlobalMeaningIndex(chapterList) {
  const index = Object.create(null);

  const addMeaning = (word, meaning) => {
    const key = normalizeWord(word);
    if (!key || !meaning) return;
    if (!index[key]) {
      index[key] = meaning;
    } else {
      const existing = index[key].split(/[；;]/).map(s => s.trim()).filter(Boolean);
      const incoming = meaning.split(/[；;]/).map(s => s.trim()).filter(Boolean);
      incoming.forEach(part => {
        if (part && !existing.includes(part)) {
          existing.push(part);
        }
      });
      index[key] = existing.join("；");
    }
  };

  chapterList.forEach(chapter => {
    (chapter.words || []).forEach(item => {
      addMeaning(item.word, item.meaning);
    });
  });
  Object.entries(COMMON_WORD_MEANINGS).forEach(([word, meaning]) => {
    addMeaning(word, meaning);
  });
  Object.entries(EXTRA_LEARNER_WORDS).forEach(([word, meaning]) => {
    addMeaning(word, meaning);
  });
  return index;
}
function meaningFromIndex(word) {
  return GLOBAL_MEANING_INDEX[normalizeWord(word)] || "";
}
function buildWordCandidates(word) {
  const normalized = normalizeWord(word);
  if (!normalized) return [];
  const candidates = new Set([normalized]);
  if (IRREGULAR_LEMMAS[normalized]) candidates.add(IRREGULAR_LEMMAS[normalized]);
  if (normalized.endsWith("'s")) candidates.add(normalized.slice(0, -2));
  if (normalized.endsWith("ies") && normalized.length > 3) candidates.add(`${normalized.slice(0, -3)}y`);
  if (normalized.endsWith("ing") && normalized.length > 4) {
    const stem = normalized.slice(0, -3);
    candidates.add(stem);
    candidates.add(`${stem}e`);
    if (/([bcdfghjklmnpqrstvwxyz])\1$/.test(stem)) candidates.add(stem.slice(0, -1));
  }
  if (normalized.endsWith("ed") && normalized.length > 3) {
    const stem = normalized.slice(0, -2);
    candidates.add(stem);
    candidates.add(`${stem}e`);
    if (/([bcdfghjklmnpqrstvwxyz])\1$/.test(stem)) candidates.add(stem.slice(0, -1));
  }
  if (normalized.endsWith("es") && normalized.length > 3) {
    candidates.add(normalized.slice(0, -2));
    if (/(ches|shes|xes|zes|ses)$/.test(normalized)) candidates.add(normalized.slice(0, -2));
  }
  if (normalized.endsWith("s") && normalized.length > 2 && !normalized.endsWith("ss")) candidates.add(normalized.slice(0, -1));
  if (normalized.endsWith("ly") && normalized.length > 4) {
    const stem = normalized.slice(0, -2);
    candidates.add(stem);
    if (stem.endsWith("i")) candidates.add(`${stem.slice(0, -1)}y`);
  }
  if (normalized.endsWith("er") && normalized.length > 3) {
    const stem = normalized.slice(0, -2);
    candidates.add(stem);
    candidates.add(`${stem}e`);
  }
  if (normalized.endsWith("est") && normalized.length > 4) {
    const stem = normalized.slice(0, -3);
    candidates.add(stem);
    candidates.add(`${stem}e`);
  }
  return [...candidates];
}
function resolveMeaning(word, chapter) {
  const normalized = normalizeWord(word);
  const savedMatch = getSavedWords(chapter).find(item => normalizeWord(item.word) === normalized && item.meaning && item.meaning.trim());
  if (savedMatch) return savedMatch.meaning;
  const direct = meaningFromIndex(normalized);
  if (direct) return direct;
  for (const candidate of buildWordCandidates(normalized)) {
    const match = meaningFromIndex(candidate);
    if (match) return candidate === normalized ? match : `${match}（原形：${candidate}）`;
  }
  return "暂无词义";
}
function categoryMeta(chapter) { return CATEGORY_META[chapter.category] || { zh: chapter.category, en: chapter.category }; }
function estimateReadTime(chapter) {
  const count = chapter.paragraphs.join(" ").split(/\s+/).filter(Boolean).length;
  return `${Math.max(1, Math.round(count / 200))} min read`;
}
function renderFilters() {
  const filterRow = el("filterRow");
  Object.entries(CATEGORY_META).forEach(([key, meta]) => {
    const button = document.createElement("button");
    button.className = "filter";
    button.dataset.filter = key;
    button.textContent = meta.zh;
    filterRow.appendChild(button);
  });
}
function renderChapters() {
  const search = el("searchInput").value.toLowerCase().trim();
  const filter = document.querySelector(".filter.active").dataset.filter;
  chapterList.innerHTML = "";
  chapters.filter(chapter => (filter === "all" || chapter.category === filter) && (`${chapter.title} ${categoryMeta(chapter).zh}`.toLowerCase().includes(search))).forEach((chapter) => {
    const index = chapters.indexOf(chapter);
    const button = document.createElement("button");
    button.className = `chapter-item ${index === currentIndex ? "active" : ""}`;
    button.innerHTML = `<span class="chapter-num">${String(chapter.id).padStart(3, "0")}</span><span><span class="chapter-title">${chapter.title}</span><span class="chapter-topic">${categoryMeta(chapter).zh}</span></span>`;
    button.addEventListener("click", () => { currentIndex = index; renderArticle(); renderChapters(); window.scrollTo({ top: 0, behavior: "smooth" }); });
    chapterList.appendChild(button);
  });
}
function tokenise(text, selectedWords = [], paragraphIndex = 0) {
  return text.split(/(\s+|[,.!?;:])/).map(part => {
    if (!part) return "";
    const clean = part.toLowerCase().replace(/[^a-z'-]/g, "");
    if (!clean || !/^[a-z'-]+$/i.test(part)) {
      return `<span class="word-sep">${part}</span>`;
    }
    const isSelected = selectedWords.some(item => item.word === clean);
    return `<span class="word ${isSelected ? "selected" : ""}" data-word="${clean}" data-para="${paragraphIndex}">${part}</span>`;
  }).join("");
}
function renderArticle() {
  const chapter = chapters[currentIndex];
  const saved = getSavedWords(chapter);
  const meta = categoryMeta(chapter);
  stopListening();
  clearAudioHighlight();
  hideWordBubble();
  translationVisible = false;
  el("translateButton").classList.remove("active");
  el("chapterNumber").textContent = String(chapter.id).padStart(3, "0");
  el("chapterCategory").textContent = meta.en.toUpperCase();
  el("readTime").textContent = estimateReadTime(chapter);
  el("progressCurrent").textContent = String(chapter.id).padStart(3, "0");
  const paragraphsZh = chapter.paragraphsZh || [];
  const bodyBlocks = chapter.paragraphs.map((p, i) => `<div class="para-block"><p class="para-en">${tokenise(p, saved, i)}</p>${paragraphsZh[i] ? `<p class="para-zh">${paragraphsZh[i]}</p>` : ""}</div>`).join("");
  articleContent.innerHTML = `<p class="article-kicker">${meta.en} / Chapter ${String(chapter.id).padStart(3, "0")}</p><h2>${chapter.title}</h2><p class="article-deck">${chapter.deck}</p><div class="article-body">${bodyBlocks}</div>`;
  articleContent.querySelectorAll(".word").forEach(word => {
    word.addEventListener("click", (e) => {
      const audio = el("articleAudio");
      const listenButton = el("listenButton");
      if (listenButton.classList.contains("playing") && audio && !audio.paused) {
        audio.pause();
        e.stopPropagation();
        return;
      }
      showWordBubble(word, word.dataset.word, findMeaning(word.dataset.word, chapter, Number(word.dataset.para)));
      e.stopPropagation();
    });
    word.addEventListener("dblclick", () => { addWord(word.dataset.word, chapter, Number(word.dataset.para)); hideWordBubble(); });
  });
  renderWords();
}
function getSavedWords(chapter) { return chapter._words || (chapter._words = getChapterWords(chapter)); }
function addWord(word, chapter, paragraphIndex) {
  const source = chapter.paragraphs.join(" ").split(/\s+/).find(item => item.toLowerCase().replace(/[^a-z'-]/g, "") === word) || word;
  chapter._words = getSavedWords(chapter);
  const normalized = normalizeWord(word);
  if (!chapter._words.some(item => normalizeWord(item.word) === normalized)) { chapter._words.push({ word: normalized, meaning: resolveMeaning(normalized, chapter, paragraphIndex), source }); showToast(`已加入「${normalized}」`); renderArticle(); }
}
function findMeaning(word, chapter, paragraphIndex) {
  return resolveMeaning(word, chapter, paragraphIndex);
}
function showWordBubble(anchor, word, meaning) {
  const bubble = el("wordBubble");
  el("wordBubbleWord").textContent = word;
  el("wordBubbleMeaning").textContent = meaning;
  bubble.dataset.word = word;
  bubble.hidden = false;
  const anchorRect = anchor.getBoundingClientRect();
  const bubbleWidth = bubble.offsetWidth || 230;
  const bubbleHeight = bubble.offsetHeight || 90;
  let left = Math.min(Math.max(anchorRect.left, 12), window.innerWidth - bubbleWidth - 12);
  let top = anchorRect.bottom + 10;
  if (top + bubbleHeight > window.innerHeight - 12) top = anchorRect.top - bubbleHeight - 10;
  bubble.style.left = `${left}px`;
  bubble.style.top = `${Math.max(top, 12)}px`;
}
function hideWordBubble() {
  const bubble = el("wordBubble");
  bubble.hidden = true;
  delete bubble.dataset.word;
}
function renderWords() {
  const words = getSavedWords(chapters[currentIndex]);
  el("wordCount").textContent = `${words.length} words`;
  wordList.innerHTML = words.length ? words.map((item, index) => `<div class="word-card"><button class="remove-word" data-remove="${index}" title="删除生词" aria-label="删除生词">×</button><strong class="word-term" data-say="${item.word}" role="button" tabindex="0">${item.word}</strong><p>${item.meaning}</p></div>`).join("") : `<div class="empty-words">还没有生词。<br />双击文章中的单词试试看。</div>`;
  wordList.querySelectorAll("[data-remove]").forEach(button => button.addEventListener("click", () => { getSavedWords(chapters[currentIndex]).splice(Number(button.dataset.remove), 1); renderArticle(); showToast("已从本篇生词表删除"); }));
  wordList.querySelectorAll(".word-term").forEach(term => term.addEventListener("click", () => speak(term.dataset.say)));
}
let cachedVoices = [];
function refreshVoices() { cachedVoices = "speechSynthesis" in window ? window.speechSynthesis.getVoices() : []; }
if ("speechSynthesis" in window) { refreshVoices(); window.speechSynthesis.onvoiceschanged = refreshVoices; }
function pickBestVoice() {
  const enVoices = cachedVoices.filter(voice => voice.lang && voice.lang.toLowerCase().startsWith("en"));
  const preferredPatterns = [/natural/i, /neural/i, /online/i, /google us english/i, /samantha/i, /aria/i];
  for (const pattern of preferredPatterns) {
    const match = enVoices.find(voice => pattern.test(voice.name));
    if (match) return match;
  }
  return enVoices.find(voice => voice.lang.toLowerCase() === "en-us") || enVoices[0] || null;
}
function speak(text) {
  if (!("speechSynthesis" in window)) return showToast("当前浏览器不支持朗读");
  window.speechSynthesis.cancel();
  const utterance = new SpeechSynthesisUtterance(text);
  const voice = pickBestVoice();
  if (voice) utterance.voice = voice;
  utterance.lang = "en-US"; utterance.rate = .88;
  window.speechSynthesis.speak(utterance);
}
let audioHighlightTimer = null;

function clearAudioHighlight() {
  if (audioHighlightTimer) {
    cancelAnimationFrame(audioHighlightTimer);
    audioHighlightTimer = null;
  }
  document.querySelectorAll(".word.audio-playing, .word-sep.audio-playing").forEach(el => {
    el.classList.remove("audio-playing");
    delete el.dataset.lastScrolled;
  });
}

function updateAudioHighlight() {
  const audio = el("articleAudio");
  if (!audio || audio.paused || !audio.duration) {
    if (audioHighlightTimer) {
      cancelAnimationFrame(audioHighlightTimer);
      audioHighlightTimer = null;
    }
    if (!audio || !audio.duration) {
      clearAudioHighlight();
    }
    return;
  }

  const wordElements = Array.from(articleContent.querySelectorAll(".word"));
  if (!wordElements.length) return;

  let totalWeight = 0;
  const weights = wordElements.map(node => {
    const text = (node.textContent || "").trim();
    let weight = text.length + 3.5;

    const nextText = node.nextSibling ? (node.nextSibling.textContent || "") : "";
    if (/[.?!]/.test(nextText)) {
      weight += 10;
    } else if (/[,;:—-]/.test(nextText)) {
      weight += 5;
    }

    const parentPara = node.closest("p");
    if (parentPara && node === parentPara.querySelector(".word:last-of-type")) {
      weight += 12;
    }

    totalWeight += weight;
    return weight;
  });

  const duration = audio.duration;
  const startOffset = 0.25;
  const endOffset = 0.35;
  const effectiveDuration = Math.max(duration - startOffset - endOffset, 0.5);
  const currentTime = Math.min(Math.max(audio.currentTime - startOffset, 0), effectiveDuration);
  const progress = currentTime / effectiveDuration;

  const targetWeight = progress * totalWeight;

  let accumulatedWeight = 0;
  let activeIndex = 0;

  for (let i = 0; i < weights.length; i++) {
    accumulatedWeight += weights[i];
    if (accumulatedWeight >= targetWeight) {
      activeIndex = i;
      break;
    }
  }
  if (progress >= 0.99) {
    activeIndex = weights.length - 1;
  }

  const activeWordNode = wordElements[activeIndex];
  const allNodes = Array.from(articleContent.querySelectorAll(".word, .word-sep"));
  const cutoffIndex = allNodes.indexOf(activeWordNode);

  allNodes.forEach((node, i) => {
    if (cutoffIndex !== -1 && i <= cutoffIndex) {
      if (!node.classList.contains("audio-playing")) {
        node.classList.add("audio-playing");
      }
    } else {
      node.classList.remove("audio-playing");
    }
  });

  if (activeWordNode && activeWordNode.dataset.lastScrolled !== String(activeIndex)) {
    activeWordNode.dataset.lastScrolled = String(activeIndex);
    activeWordNode.scrollIntoView({ behavior: "smooth", block: "nearest", inline: "nearest" });
  }

  audioHighlightTimer = requestAnimationFrame(updateAudioHighlight);
}

function toggleTranslation() {
  translationVisible = !translationVisible;
  const body = articleContent.querySelector(".article-body");
  if (body) body.classList.toggle("show-translation", translationVisible);
  el("translateButton").classList.toggle("active", translationVisible);
}
function toggleListen() {
  const button = el("listenButton");
  if (button.classList.contains("playing")) { stopListening(); return; }
  const chapter = chapters[currentIndex];
  const audio = el("articleAudio");
  let retryCount = 0;

  audio.onerror = () => {
    if (retryCount < 2) {
      retryCount++;
      audio.load();
      audio.play().catch(() => {});
      return;
    }
    stopListening();
    showToast(`第${chapter.id}篇音频文件加载失败，请重试`);
  };
  audio.onended = stopListening;
  audio.ontimeupdate = updateAudioHighlight;
  audio.onplay = () => {
    retryCount = 0;
    updateAudioHighlight();
  };
  audio.onpause = () => {
    if (audioHighlightTimer) {
      cancelAnimationFrame(audioHighlightTimer);
      audioHighlightTimer = null;
    }
  };

  audio.src = `audio/${String(chapter.id).padStart(3, "0")}.mp3`;
  button.classList.add("playing");
  button.textContent = "停止播放";
  button.title = "停止播放";
  button.setAttribute("aria-label", "停止播放");
  audio.play().catch(() => {
    stopListening();
    showToast("音频播放失败，请检查网络或浏览器设置");
  });
}
function stopListening() {
  if ("speechSynthesis" in window) window.speechSynthesis.cancel();
  clearAudioHighlight();
  const audio = el("articleAudio");
  audio.onerror = null;
  audio.onplay = null;
  audio.onpause = null;
  audio.pause();
  const button = el("listenButton");
  button.classList.remove("playing");
  button.textContent = "播放文章";
  button.title = "播放文章";
  button.setAttribute("aria-label", "播放文章");
}
function showToast(message) { const toast = el("toast"); toast.textContent = message; toast.classList.add("show"); clearTimeout(showToast.timeout); showToast.timeout = setTimeout(() => toast.classList.remove("show"), 2200); }
async function toggleRecording() {
  if (mediaRecorder?.state === "recording") { mediaRecorder.stop(); return; }
  if (!navigator.mediaDevices?.getUserMedia) return showToast("当前浏览器不支持录音");
  try {
    const stream = await navigator.mediaDevices.getUserMedia({ audio: true });
    audioChunks = []; mediaRecorder = new MediaRecorder(stream);
    mediaRecorder.ondataavailable = event => audioChunks.push(event.data);
    mediaRecorder.onstop = () => { const blob = new Blob(audioChunks, { type: "audio/webm" }); el("recordingPlayer").src = URL.createObjectURL(blob); el("recordingPlayer").hidden = false; stream.getTracks().forEach(track => track.stop()); stopRecordingUI(); showToast("录音完成，可以试听"); };
    mediaRecorder.start(); recordingSeconds = 0; recordingInterval = setInterval(() => { recordingSeconds++; el("recordingTime").textContent = formatTime(recordingSeconds); }, 1000); el("recordButton").innerHTML = `<span class="record-symbol">■</span> 结束录音`; el("recordingStatus").textContent = "正在录音"; el("micDot").classList.add("recording");
  } catch { showToast("没有获得麦克风权限"); }
}
function stopRecordingUI() { clearInterval(recordingInterval); el("recordButton").innerHTML = `<span class="record-symbol">●</span> 开始录音`; el("recordingStatus").textContent = "录下你的声音"; el("micDot").classList.remove("recording"); }
function formatTime(seconds) { return `${String(Math.floor(seconds / 60)).padStart(2, "0")}:${String(seconds % 60).padStart(2, "0")}`; }

renderFilters();
articleContent.addEventListener("click", (e) => {
  const audio = el("articleAudio");
  const listenButton = el("listenButton");
  if (!listenButton.classList.contains("playing") || !audio || !audio.src) return;
  if (e.target.closest(".word")) return;

  if (!audio.paused) {
    audio.pause();
  } else {
    audio.play().catch(() => {});
  }
});
el("wordBubbleAudio").addEventListener("click", () => { const word = el("wordBubble").dataset.word; if (word) speak(word); });
document.addEventListener("click", event => { const bubble = el("wordBubble"); if (bubble.hidden || bubble.contains(event.target) || event.target.classList.contains("word")) return; hideWordBubble(); });
document.addEventListener("keydown", event => { if (event.key === "Escape") hideWordBubble(); });
window.addEventListener("scroll", () => hideWordBubble(), true);
el("filterRow").addEventListener("click", event => { if (!event.target.matches(".filter")) return; document.querySelectorAll(".filter").forEach(button => button.classList.remove("active")); event.target.classList.add("active"); renderChapters(); });
el("searchInput").addEventListener("input", renderChapters);
el("listenButton").addEventListener("click", toggleListen);
el("translateButton").addEventListener("click", toggleTranslation);
el("copyButton").addEventListener("click", async () => { const chapter = chapters[currentIndex]; try { await navigator.clipboard.writeText(`${chapter.title}\n\n${chapter.paragraphs.join("\n\n")}`); showToast("全文已复制"); } catch { showToast("复制失败，请手动选择文字"); } });
el("prevButton").addEventListener("click", () => { currentIndex = (currentIndex - 1 + chapters.length) % chapters.length; renderArticle(); renderChapters(); });
el("nextButton").addEventListener("click", () => { currentIndex = (currentIndex + 1) % chapters.length; renderArticle(); renderChapters(); });
el("fontDown").addEventListener("click", () => { fontScale = Math.max(.9, fontScale - .05); document.documentElement.style.setProperty("font-size", `${fontScale}rem`); el("fontSizeLabel").textContent = `${Math.round(fontScale * 100)}%`; });
el("fontUp").addEventListener("click", () => { fontScale = Math.min(1.15, fontScale + .05); document.documentElement.style.setProperty("font-size", `${fontScale}rem`); el("fontSizeLabel").textContent = `${Math.round(fontScale * 100)}%`; });
el("recordButton").addEventListener("click", toggleRecording);
el("deleteRecordButton").addEventListener("click", () => { el("recordingPlayer").removeAttribute("src"); el("recordingPlayer").hidden = true; stopRecordingUI(); el("recordingTime").textContent = "00:00"; recordingSeconds = 0; showToast("录音已删除"); });
renderArticle(); renderChapters();
